### ISSUE TITLE
Add babelScript (es6)

### ISSUE THREAD

**Issue by yangli-io** [yangli1990/Node-Server#2]
this can be achieved through the babel npm module.

look into the 'babel register hook'

**Comment by KbRama** [comment]
will do this today.

**Comment by KbRama** [comment]
```
babel is the main core babel project that allows us to set up our development environment
babel-eslint is a parser for eslint that teaches the linter about experimental features that aren’t in ES6.
eslint is a linting tool and eslint-config-standard is a set of configurations for eslint that we’ll write our code against which follows the JS Standard style.
babel-tape-runner hooks in babel when running tape and blue-tape is an extension to tape that adds promise support (which will come in handy in a bit).
```

**Comment by yangli-io** [comment]
?

**Comment by KbRama** [comment]
Babel has built in a source-map support for browsers and proper stack traces for Node, so it gets out of the way for you to focus on the ES6 code... is this really necessary ?

**Comment by KbRama** [comment]
what about the upcoming ES7 ?....will they still use BABEL or Traceur ?

**Comment by yangli-io** [comment]
babel just lets us write ES6 and ES7.  No it's not neccessary, you can skip this if you want.

**Comment by KbRama** [comment]
ok...will do it... nice to know. But think some day it might be embedded into node.

**Comment by yangli-io** [comment]
okay then, what do you want to do now?  You've done node, express - I think you're ready for the real world

**Comment by KbRama** [comment]
Added  httpServerBabel.js, calling the express code with in this, added babel as a dependency.
Let me know if this is right.

**Comment by KbRama** [comment]
let move on... let me know the next one.

**Comment by KbRama** [comment]
done!!

**Comment by yangli-io** [comment]
Theres a task in your pull request to remove some of the files
