### ISSUE TITLE
Added gitter chat

### ISSUE THREAD

**Issue by yangli-io** [yangli1990/Node-Server#3]
@KarthikBangaloreVenkatarama Added gitter chat badge in the Readme.md you can go there and type your thoughts.

**Comment by KbRama** [comment]
ok done.

**Comment by yangli-io** [comment]
Stop merging to master, just create the pull request and we can go through a review process

**Comment by KbRama** [comment]
yeh...green button was very tempting to be pressed :)

**Comment by yangli-io** [comment]
You're fired. lol

**Comment by yangli-io** [comment]
Did you add anything apart from package.json?

**Comment by KbRama** [comment]
no not yet...will update the code with express.
